export const ProductData = [
  {
    ProductNo: "001",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle31.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "150000vnd",
    ProductCharacteristic: "Bột",
    ProductType: "Hạt giống",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "50 hạt/gói",
    ProductWeight: "200g/gói",
  },
  {
    ProductNo: "002",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle30.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "75000vnd",
    ProductCharacteristic: "Nước",
    ProductType: "Cây trồng",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "70 hạt/gói",
    ProductWeight: "300g/gói",
  },
  {
    ProductNo: "003",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle9.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "45000vnd",
    ProductCharacteristic: "Viên",
    ProductType: "Hệ thống thủy canh",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "70 hạt/gói",
    ProductWeight: "400g/gói",
  },
  {
    ProductNo: "004",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle31.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "100000vnd",
    ProductCharacteristic: "Bột",
    ProductType: "Rau củ",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "70 hạt/gói",
    ProductWeight: "300g/gói",
  },
  {
    ProductNo: "005",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle31.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "300000vnd",
    ProductCharacteristic: "Bột",
    ProductType: "Thuốc trừ sâu",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "70 hạt/gói",
    ProductWeight: "300g/gói",
  },
  {
    ProductNo: "006",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle9.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "125000vnd",
    ProductCharacteristic: "Viên",
    ProductType: "Dụng cụ",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "70 hạt/gói",
    ProductWeight: "367g/gói",
  },
  {
    ProductNo: "007",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle30.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "12000vnd",
    ProductCharacteristic: "Nước",
    ProductType: "Hạt giông",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "87 hạt/gói",
    ProductWeight: "420g/gói",
  },
  {
    ProductNo: "008",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle31.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "50000vnd",
    ProductCharacteristic: "Bột",
    ProductType: "Phân bón",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "79 hạt/gói",
    ProductWeight: "330g/gói",
  },
  {
    ProductNo: "009",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle9.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "50000vnd",
    ProductCharacteristic: "Viên",
    ProductType: "Thuốc trừ sâu",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "70 hạt/gói",
    ProductWeight: "300g/gói",
  },
  {
    ProductNo: "010",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle30.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "76000vnd",
    ProductCharacteristic: "Nước",
    ProductType: "Phân bón",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "70 hạt/gói",
    ProductWeight: "300g/gói",
  },
  {
    ProductNo: "011",
    ProductName: "Hạt giống cải xanh",
    ProductImage: [process.env.PUBLIC_URL + "images/product/Rectangle30.png"],
    ProductDescription: "Rau ngắn ngày",
    ProductPrice: "99000vnd",
    ProductCharacteristic: "Nước",
    ProductType: "Phân bón",
    ProductDetail:
      "Hạt giống cải xanh thuộc công ty ABC có chất lượng tốt, dễ dàng ủ giống và trồng, tỉ lệ lên mầm cao. Giống cải thành phẩm xanh, to, có chất lượng cao Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt",
    ProductSummary: [
      "Hạt giống thủy canh rau xanh là những giống cây được ưa chuộng trong phương pháp canh tác thủy canh, một phương pháp trồng cây mà không cần đất phục vụ cho việc sinh trưởng. Nhờ vào việc sử dụng nước và dung dịch dinh dưỡng phân hủy, hạt giống thủy canh rau xanh phát triển mạnh mẽ và nhanh chóng, đồng thời mang lại năng suất cao và chất lượng tốt.",
      " Khí hậu trồng: cả xứ nóng & xứ lạnh",
      ". Thu hoạch sau 32 - 35 ngày",
    ],
    ProductQuantity: "70 hạt/gói",
    ProductWeight: "300g/gói",
  },
];
